# create a config file for the labeler action

# Define the labels to be used
labels:
  - name: fix
    color: ffff00
  - name: feature
    color: 00ff00
  - name: bug
    color: ff0000
  - name: documentation
    color: 0000ff
  - name: chore
    color: 000000
  - name: test
    color: 00ffff
  - name: ci
    color: ff00ff
  - name: refactor
    color: 0000ff
  - name: style
    color: 00ff00
  - name: performance
    color: ff0000
  - name: security
    color: ff0000

# Define the rules for the labels
rules:
  - labels:
      - fix
      - bug
    pattern: ^fix.*$
  - labels:
      - feature
    pattern: ^feat.*$
  - labels:
      - documentation
    pattern: ^docs.*$
  - labels:
      - chore
    pattern: ^chore.*$
  - labels:
      - test
    pattern: ^test.*$
  - labels:
      - ci
    pattern: ^ci.*$
  - labels:
      - refactor
    pattern: ^refactor.*$
  - labels:
      - style
    pattern: ^style.*$
  - labels:
      - performance
    pattern: ^perf.*$
  - labels:
      - security
    pattern: ^security.*$
